### ISSUE TITLE
Masking clarification

### ISSUE THREAD

**Issue by neurofractal** [pactools/pactools#18]
Thanks for a great set of PAC tools. I'm currently comparing the results with my MATLAB code. I have a couple of questions from the [plot_mne_epoch_masking](https://github.com/pactools/pactools/blob/master/examples/plot_mne_epoch_masking.py) tutorial:

- Do you mask the data **after** band-pass filtering?
- Do you calculate PAC on single trials, then average... or use the continuously masked data?

**Comment by TomDLT** [comment]
- Masking is done **after** filtering:
https://github.com/pactools/pactools/blob/f1ed7095e3dbd663001facaf5646c59c74aaec38/pactools/comodulogram.py#L185-L187
This is important since masking concatenates unrelated parts of the signal, so you do not want to filter after masking.

- PAC is averaged across epochs, and computed on each mask independently:
https://github.com/pactools/pactools/blob/f1ed7095e3dbd663001facaf5646c59c74aaec38/pactools/comodulogram.py#L197-L200
In https://pactools.github.io/auto_examples/plot_mne_epoch_masking.html, you can see 6 plots corresponding to the 6 masks, corresponding to the 6 events in the MNE object.
