### ISSUE TITLE
Where did randomisation procedure happen and what the purpose of it?

### ISSUE THREAD

**Issue by hyphenzhao** [pactools/pactools#36]
First of all, this is a great work and I found it works very well with simulated data. I would like to explore more with my real-life data. However, everytime I calculated the PAC with this toolbox with method='duprelatour', I got different result. I understand that surrogate may have happened but since I would like to control this random process therefore I would rather shift the phase by my own function instead of using randomisation procedure.
However, even if I use the parameter like this:

    comod = Comodulogram(fs=epochs.info['sfreq'], low_fq_range=fq_range[0], high_fq_range=fq_range[1], 
                         n_surrogates=0, n_jobs=None,
                         progress_bar=True, 
                         minimum_shift=1,
                         method='duprelatour')

I still got different results every time. I am wondering of which function did the randomisation happen? 
Thanks.

**Comment by TomDLT** [comment]
With `method="duprelatour"`, the method estimates a full spectrum using a DAR model, which works best on spectrum that don't have a gap. Because removing the low-frequency signal introduces a frequency gap, we fill the gap with some Gaussian white noise, filtered to matched the spectrum of the removed low-frequency signal. This should be the only non-deterministic part of the method.

To always use the same Gaussian noise signal (and make the method deterministic), you can set `Comodulogram(..., random_state=42)`.

**Comment by hyphenzhao** [comment]
> With `method="duprelatour"`, the method estimates a full spectrum using a DAR model, which works best on spectrum that don't have a gap. Because removing the low-frequency signal introduces a frequency gap, we fill the gap with some Gaussian white noise, filtered to matched the spectrum of the removed low-frequency signal. This should be the only non-deterministic part of the method.
> 
> To always use the same Gaussian noise signal (and make the method deterministic), you can set `Comodulogram(..., random_state=42)`.

Thanks, Tom! That clarifies out my considerations! So great work.
FYI, I tried DAR based PAC on my dataset. And it was consistent when it was performed on long-time series but usually unstable when applied on epoched short time series data. However, if the PAC is strong enough (for my case is hypothesized emotion stimulus), the PAC kept consistent even when the epoch time is short.
Anyway, thanks for your reponse.
