### ISSUE TITLE
[Request] Save comodulogram

### ISSUE THREAD

**Issue by fraimondo** [pactools/pactools#5]
I'm currently working on a project and I plan to use this tool to compute PAC on several subjects. Since it takes quite some time, I would like to save the comodulograms on files, to be able to do the analysis later.

Are you interested in such a feature? I will do it in any case, but if you are interested, we can discuss a proper way and add it to your tool.

**Comment by TomDLT** [comment]
That would be nice indeed.
I usually save only the comod array with `np.save`, but it would be better to save also some class attributes.

One off-the-shelf solution would be to use `joblib.dump`, which handles arbitrary python object.
Another idea would be to save a dictionary or attribute in Matlab file with `scipy.io.savemat`, since some users could be interested in post-processing it with Matlab.

What do you think?

**Comment by fraimondo** [comment]
I would go for h5io (https://github.com/h5io/h5io <https://github.com/h5io/h5io>)

That way it can also be loaded from Matlab. And it handles numpy structures very well.

Basically comodulograms could be saved and loaded from a file.

**Comment by TomDLT** [comment]
Excellent !

**Comment by fraimondo** [comment]
I'll work on it and propose a pull request.

Le 8 déc. 2017 5:53 PM, "Tom Dupré la Tour" <notifications@github.com> a
écrit :
